spring:
  profiles:
    active:
    default: local
  h2:
    console:
      enabled: true  # H2 Console을 사용할지 여부 (H2 Cobnsole은 H2 Dataase를 UI로 제공해주는 기능)
      path: /h2-console  # H2 Console의 Path
  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
  datasource:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:~/test  # H2 접속 정보
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력) ''

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate:
        default_batch_fetch_size: 1000
riot:
  api:
    key: ENC(vtzgWQRmgbuuHcOg0z48XgOkQHXAqjyvNQCvfqEVwSNldxJO4pGrFZ2tkg/zw/8Uw2V8ylsZP7s=)
    ##riot key 입력

server:
  port: 8080

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )
---
